---
title: |
  <center> CHAD Output Summary </center>
subtitle: |
  <center> `r format(Sys.time(), '%d %B, %Y')` </center>
  
author: 
date:
output: powerpoint_presentation
always_allow_html: true

---


---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
# Some global stuff
library(ggplot2)
library(plotly)
library(knitr)
library(kableExtra)


CountyDT = GetLocalDataTable(MyCounties)

```



### Daily Case Chart

```{r echo=FALSE}
DailyChart <- CovidCasesPerDayChart(MyCounties)
    DailyChart <- dplyr::filter(DailyChart, ForecastDate >= DailyChart$ForecastDate[1] + 35)
    
    plotDaily <- ggplot(DailyChart) + 
      geom_line(aes(x=ForecastDate, y=value, colour = variable), size = 0.5) +
      scale_colour_manual(values=c("Blue", "Red")) +
      xlab('Date') +
      ylab('Number of People') +
      theme_bw() + 
      theme(plot.title = element_text(face = "bold", size = 15, family = "sans"),
            axis.title = element_text(face = "bold", size = 11, family = "sans"),
            axis.text.x = element_text(angle = 60, hjust = 1), 
            axis.line = element_line(color = "black"),
            legend.position = "top",
            plot.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank()) +
      scale_x_date(date_breaks = "1 week") +
      labs(color='')
    
    plotDaily <- ggplotly(plotDaily)
    plotDaily <- plotDaily %>% layout(legend = list(orientation = "h",   # show entries horizontally
                                                    xanchor = "center",  # use center of legend as anchor
                                                    x = 0.5,
                                                    y = 1.2)) %>% config(displayModeBar = FALSE)
    plotDaily
```

### 3-Day Moving Average

```{r echo=FALSE}
DailyChart <- CovidCasesPer3DayAverageChart(MyCounties)
    DailyChart <- dplyr::filter(DailyChart, ForecastDate >= DailyChart$ForecastDate[1] + 35)
    
    plotDaily <- ggplot(DailyChart) + 
      geom_col(aes(x=ForecastDate, y=value, colour = variable), size = 0.5) +
      scale_colour_manual(values=c("Blue", "Red")) +
      xlab('Date') +
      ylab('Number of People') +
      theme_bw() + 
      theme(plot.title = element_text(face = "bold", size = 15, family = "sans"),
            axis.title = element_text(face = "bold", size = 11, family = "sans"),
            axis.text.x = element_text(angle = 60, hjust = 1), 
            axis.line = element_line(color = "black"),
            legend.position = "top",
            plot.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank()) +
      scale_x_date(date_breaks = "1 week") +
      labs(color='')
    
    plotDaily <- ggplotly(plotDaily)
    plotDaily <- plotDaily %>% layout(legend = list(orientation = "h",   # show entries horizontally
                                                    xanchor = "center",  # use center of legend as anchor
                                                    x = 0.5,
                                                    y = 1.2)) #%>% config(displayModeBar = FALSE)
    plotDaily
```

### Total Cases

```{r echo=FALSE}
CumulChart <- CovidCasesCumChart(MyCounties)
    CumulChart <- dplyr::filter(CumulChart, ForecastDate >= CumulChart$ForecastDate[1] + 35)
    
    #Plot for local area cumulative cases
    plotTot <- ggplot(CumulChart) + 
      geom_line(aes(x=ForecastDate, y=value, colour = variable), size = 0.5) +
      scale_colour_manual(values=c("Blue", "Red", "Green"))+
      xlab('Date') +
      ylab('Number of People') +
      theme_bw() + 
      theme(plot.title = element_text(face = "bold", size = 15, family = "sans"),
            axis.title = element_text(face = "bold", size = 11, family = "sans"),
            axis.text.x = element_text(angle = 60, hjust = 1), 
            axis.line = element_line(color = "black"),
            plot.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank(),
            legend.position = c(0, 1),) +
      scale_x_date(date_breaks = "1 week")
    
    plotTot <- ggplotly(plotTot)
    plotTot <- plotTot %>% layout(legend = list(orientation = "h",   # show entries horizontally
                                                xanchor = "center",  # use center of legend as anchor
                                                x = 0.5,
                                                y = 1.2)) #%>% config(displayModeBar = FALSE)
    plotTot
```

### Weekly Growth Rate

```{r echo=FALSE}
 DailyChart <- CovidCasesWeeklyGrowth(MyCounties)
    
    plotDaily <- ggplot(DailyChart) + 
      geom_col(aes(x=`Forecast Date`, 
                   y=value, 
                   fill = ifelse(value>0, 
                                 "Growth Increase", 
                                 "Growth Decrease")), 
               size = 0.5) +
      scale_fill_manual(values=c("Green", "Red"),
                        name = "Case Growth") +
      geom_hline(aes(yintercept = 0),
                 colour = "black",
                 linetype = "dashed") +
      xlab('Date') +
      ylab('Weekly Growth Rate') +
      theme_bw() + 
      theme(plot.title = element_text(face = "bold", size = 15, family = "sans"),
            axis.title = element_text(face = "bold", size = 11, family = "sans"),
            axis.text.x = element_text(angle = 60, hjust = 1), 
            axis.line = element_line(color = "black"),
            legend.position = "top",
            plot.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank()) +
      scale_x_date(date_breaks = "1 week") +
      scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
      #ylim(0,max(Chart1DataSub$value) * 1.1) +
      labs(color='')
    
    plotDaily <- ggplotly(plotDaily)
    plotDaily <- plotDaily %>% layout(legend = list(orientation = "h",   # show entries horizontally
                                                    xanchor = "center",  # use center of legend as anchor
                                                    x = 0.5,
                                                    y = 1.2)) #%>% config(displayModeBar = FALSE)
    plotDaily
```

### Region Statistics

```{r echo=FALSE}
CountyDT
#kable(CountyDT) %>%
#  kable_styling(bootstrap_options = c("striped", "hover"))
```


