# Step One
###################################################################################################################################################
#Loads in all necessary packages for the shiny app

library(stringr)
library(purrr)
library(markdown)
library(dplyr)
library(ggplot2)
library(tidyr)
library(shinydashboard)
library(shiny)
library(geosphere)
library(scales)
library(googleVis)
library(usmap)
library(data.table)
library(plyr)
library(jsonlite)
library(splitstackshape)
library(DT)
library(mapproj)
library(viridis)
library(tidyverse)
library(zoo) #used for rollsum function 
library(rmarkdown)
library(rvest)
library(maps)
library(tm)
library(sf)
library(ggrepel)
library(tigris)
library(plotly)
library(vroom)
library(base64enc)
library(Matrix)
library(pkgload)
library(R.utils)
